# Generated by Django 5.1 on 2025-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
