# Generated by Django 5.1 on 2025-01-21 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id_license', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('date_expiration', models.DateField()),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=50)),
                ('game_datetime', models.DateTimeField(auto_now_add=True)),
                ('predicted', models.IntegerField()),
                ('total_hits', models.IntegerField()),
                ('predicted_hits', models.IntegerField()),
                ('v1l', models.IntegerField()),
                ('v2l', models.IntegerField()),
                ('v3l', models.IntegerField()),
                ('v4l', models.IntegerField()),
                ('numbers_to_predict', models.IntegerField()),
                ('previous_numbers', models.IntegerField()),
                ('neighbor_count', models.IntegerField()),
                ('game_limit', models.IntegerField()),
                ('probability', models.FloatField()),
                ('effectiveness', models.FloatField()),
                ('roulette', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='backend.user')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id_user_license', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_licenses', to='backend.license')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_license', to='backend.user')),
            ],
            options={
                'db_table': 'user_licenses',
            },
        ),
    ]
