# Generated by Django 5.1 on 2025-01-19 22:59

from django.db import migrations


def create_initial_data(apps, schema_editor):
    User = apps.get_model('backend', 'User')
    Report = apps.get_model('backend', 'Report')
    License = apps.get_model('backend', 'License')
    from datetime import date

    # Crear usuarios
    user1 = User.objects.create(email='user1@example.com', name='User One', password='password1')
    user2 = User.objects.create(email='user2@example.com', name='User Two', password='password2')

    # Crear reportes
    Report.objects.create(
        user=user1,
        game='Game One',
        predicted=10,
        total_hits=5,
        predicted_hits=3,
        v1l=1,
        v2l=2,
        v3l=3,
        v4l=4,
        numbers_to_predict=5,
        previous_numbers=10,
        neighbor_count=2,
        game_limit=20,
        probability=0.75,
        effectiveness=0.85,
        roulette='Roulette One',
        description='Description for report one'
    )

    Report.objects.create(
        user=user2,
        game='Game Two',
        predicted=15,
        total_hits=7,
        predicted_hits=5,
        v1l=2,
        v2l=3,
        v3l=4,
        v4l=5,
        numbers_to_predict=6,
        previous_numbers=12,
        neighbor_count=3,
        game_limit=25,
        probability=0.80,
        effectiveness=0.90,
        roulette='Roulette Two',
        description='Description for report two'
    )

    # Crear licencias
    License.objects.create(key='LICENSEKEY1', user=user1, date_expiration=date(2025, 12, 31))
    License.objects.create(key='LICENSEKEY2', user=user2, date_expiration=date(2025, 12, 31))


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
