# Generated by Django 5.1 on 2025-01-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_create_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('ruleta', models.CharField(max_length=100)),
                ('cantidad_vecinos', models.IntegerField()),
                ('numero_tardanza', models.IntegerField()),
                ('umbral_probabilidad', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='backend.user')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
