# Generated by Django 5.1 on 2025-02-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id_juego',
            new_name='id_game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='ruleta',
            new_name='nombre_ruleta',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='numero_tardanza',
            new_name='tardanza',
        ),
        migrations.RemoveField(
            model_name='report',
            name='v4l',
        ),
    ]
