# Generated by Django 5.1 on 2025-05-27 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=50)),
                ('game_datetime', models.DateTimeField(auto_now_add=True)),
                ('predicted', models.IntegerField()),
                ('total_hits', models.IntegerField()),
                ('predicted_hits', models.IntegerField()),
                ('v1l', models.IntegerField()),
                ('v2l', models.IntegerField()),
                ('v3l', models.IntegerField()),
                ('numbers_to_predict', models.IntegerField()),
                ('previous_numbers', models.IntegerField()),
                ('neighbor_count', models.IntegerField()),
                ('game_limit', models.IntegerField()),
                ('probability', models.FloatField()),
                ('effectiveness', models.FloatField()),
                ('roulette', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
