# Generated by Django 5.1 on 2025-05-01 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id_license', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('date_expiration', models.DateField()),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id_user_license', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_licenses', to='licenses.license')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_license', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_licenses',
            },
        ),
    ]
